### ISSUE TITLE
To-Do List for Work tab

### ISSUE THREAD

**Issue by arimulligan** [arimulligan/the-dove#1]
Fleshed out need to implement so my brain doesn't fry:

- [x] #13
  - [x] input, and change totalTime according to number
  - [x] Enter key listener for submitting 
  - [x] input will pop underneath the edit timer button with placeholder as current interval
- [x] #7
- [x] add in minutes, not seconds.
- [x] #8
  - [x] need to add in list functionality like the to-do list but with adjustments: cannot drop/drag (there's no point), and a toggle for the trash can icon.
  - [x] need to add in website blocking when pressed enter on keywords.
- [x] #24
  - [x] #10
  - [x] end rest early -> stops timer and starts work session (back to norm)
